language: c

compiler: 
    - gcc

env:
  - KERNEL_VERSION=4.4.0-78-generic

notifications:
    mail: "mbehr@mcbehr.de"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y linux-headers-$KERNEL_VERSION

script:
  - make BUILD_KERNEL_VERSION=$KERNEL_VERSION

